spring.application.name=koina
spring.datasource.url=jdbc:postgresql://localhost:5433/db_koina
spring.datasource.username=postgres
spring.datasource.password=05022005

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web=DEBUG

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect